name: Linter
on:
  pull_request:
    branches:
      - master
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle-aggregate
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.10.2
    - name: Run reviewdog check
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.CI_CD }}
      run: |
        cat target/checkstyle-result.xml | reviewdog -f=checkstyle -diff="git diff master" -reporter=github-pr-check
    - name: Misspell
      uses: reviewdog/action-misspell@v1
      with:
        github_token: ${{ secrets.CI_CD }}
        locale: "US"
        level: info
        reporter: github-pr-review

